### ISSUE TITLE
Clicking on Proxy Host or Proxy User name stalls app

### ISSUE THREAD

**Issue by TuxPaper** [BiglySoftware/BiglyBT-Android#142]
When in Proxy Settings, clicking either the Host or the User Name entry stalls the app.  The app must be killed to get the UI to run again.

**Comment by randal007** [comment]
I have the same problem, driving me crazy!

**Comment by gadelkareem** [comment]
It happens with port in my case

**Comment by TuxPaper** [comment]
should be fixed in the latest release, v1.3.0.2.  Thank you for your patience.

**Comment by randal007** [comment]
> should be fixed in the latest release, v1.3.0.2. Thank you for your patience.

Just tested with 1.3.0.2 on the newest nivida shield pro. Still crashes when saving a port number. Issue not fixed :(

**Comment by TuxPaper** [comment]
Inconceivable!

Just updated my nVidia's OS, and sure enough, it crashes again.
I've checked on a tablet, and setting port there doesn't crash, so I guess it's a new bug. :(

**Comment by TuxPaper** [comment]
Fixed in v1.3.0.8.  This time for sure, surely!
